<?php

function libre_scholar_anonymous_islandora_object_access($op, $object, $user) {
  $ops = array(
    'view fedora repository objects',
    'manage object properties',
    'regenerate derivatives for an object',
    'delete fedora objects and datastreams',
    'edit fedora metadata',
    'add fedora datastreams',
    'ingest fedora objects',
    'manage collection policy',
    'migrate collection members',
    'replace a datastream with new content, preserving version history',
    'revert to old datastream',
  );
  if ($object->state == 'I' && in_array($op, $ops) && !user_access('manage inactive objects')) {
    return FALSE;
  }
}

/**
 * Implements hook_islandora_datastream_access().
 */
function libre_scholar_anonymous_islandora_datastream_access($op, $object, $user) {
  $ops = array(
    'view fedora repository objects',
    'manage object properties',
    'regenerate derivatives for an object',
    'delete fedora objects and datastreams',
    'edit fedora metadata',
    'add fedora datastreams',
    'ingest fedora objects',
    'manage collection policy',
    'migrate collection members',
    'replace a datastream with new content, preserving version history',
    'revert to old datastream',
  );

  if ($object->parent->state == 'I' && in_array($op, $ops) && !user_access('manage inactive objects')) {
    return FALSE;
  }
}